---

- hosts: all
  roles:
    - contrail-common-libs
    - contrail-controller-hacks
    - packaging-prepare-contrail-centos
    - yum-repos-prepare
    - install-pip-virtualenv
    - contrail-unittests-centos

